server:
  port: 80

eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    service-url:
      #集群指向其它eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机就是7001自己 即http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/


feign:
  hystrix:
    enabled: true